# Generated by Django 5.0.1 on 2024-03-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuition', '0003_alter_tuitionmodel_day_perweek'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('tuition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.teachermodel')),
            ],
        ),
    ]
