# Generated by Django 5.0.1 on 2024-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionmodel',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
