# Generated by Django 5.0.1 on 2024-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_tuitionmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionmodel',
            name='day_perweek',
            field=models.CharField(choices=[('3_Days', 3), ('4_Days', 4), ('5_Days', 5), ('6_Days', 6)], max_length=10),
        ),
    ]
