# Generated by Django 5.0.1 on 2024-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_alter_tuitionmodel_day_perweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionmodel',
            name='category',
            field=models.CharField(choices=[('Bangla Medium', 'Bangla Medium'), ('English Medium', 'English Medium'), ('English Version', 'English Version')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tuitionmodel',
            name='no_of_student',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tuitionmodel',
            name='subject',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tuitionmodel',
            name='tuition_duration',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tuitionmodel',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tuitionmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
