# Generated by Django 5.0.1 on 2024-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_tuitionmodel_category_tuitionmodel_no_of_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionmodel',
            name='day_perweek',
            field=models.CharField(choices=[('3 Days', 3), ('4 Days', 4), ('5 Days', 5), ('6 Days', 6)], max_length=10),
        ),
    ]
