# Generated by Django 5.0.1 on 2024-03-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_teachermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='education',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'HONOURS'), ('MASTERS', 'MASTERS')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
