# Generated by Django 5.0.1 on 2024-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_teachermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/teachers'),
        ),
    ]
