# Generated by Django 5.0.1 on 2024-04-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teacherimagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherImageModel',
        ),
    ]
