# Generated by Django 5.0.1 on 2024-04-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_teacherimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='image',
        ),
    ]
